name: negative-allowlist
on:
  push:
    branches: [negative-allowlist]
permissions:
  id-token: write
  contents: read
  deployments: write
  statuses: write
jobs:
  deny:
    uses: 1REALTOUR/vercel-prebuilt/.github/workflows/vercel-prebuilt.yml@main
    with:
      environment: preview
      vercel_org_id: team_UALWOt3DTheRA6BwvmzIA2iD
      vercel_project_id: prj_not_used
      runner: ubuntu-latest
      node_version: "22"
